model: deepseek-chat
base_url: https://api.deepseek.com
temperature: 1.0
iteration: 2
sample: 2
output_dir: outputs/eureka_numeric_irl
env_name: ant
env_description: Train an Ant policy to move forward stably with smooth control.

inner:
  env_name: Ant-v4
  seed: 2026
  device: cuda:0
  sac_epochs: 1
  sac_steps_per_epoch: 1000
  sac_log_step_interval: 1000
  max_ep_len: 1000
  training_trajs: 2
  irl_iterations: 1
  reward_grad_steps: 10
  reward_lr: 0.01
