model: deepseek-chat
base_url: https://api.deepseek.com
temperature: 1.0
iteration: 2
sample: 2
output_dir: outputs/eureka_numeric_irl
env_name: walker2d
env_description: Train a Walker2d policy to move forward stably with smooth control.

inner:
  env_name: Walker2d-v4
  seed: 2026
  device: cuda:0
  objective: maxentirl_sa
  expert_episodes: 1
  resample_episodes: 1
  sac_epochs: 1000
  sac_steps_per_epoch: 1000
  sac_log_step_interval: 5000
  max_ep_len: 1000
  training_trajs: 10
  irl_iterations: 1
  reward_grad_steps: 1
  reward_lr: 0.0001
  reward_weight_decay: 0.001
  reward_momentum: 0.9
  learning_starts: 10000
  buffer_size: 1000000
  num_test_episodes: 10
  grad_clip_norm: 10.0
